/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CYCard: typeof import('./src/components/CYCard.vue')['default']
    CYDraggable: typeof import('./src/components/CYDraggable.vue')['default']
    CYEllipsis: typeof import('./src/components/CYEllipsis.vue')['default']
    CYIconText: typeof import('./src/components/CYIconText.vue')['default']
    CYPane: typeof import('./src/components/CYPane.vue')['default']
    CYSplitpanes: typeof import('./src/components/CYSplitpanes.vue')['default']
    CYSteps: typeof import('./src/components/CYSteps.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    PointCloud: typeof import('./src/components/pointCloud.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
